repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        name: ruff lint
        args: ["--select", "I", "--fix"]
        files: ^pyfileindex/
      - id: ruff-format
        name: ruff format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.720'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
