matrix:
  include:
    - name: test_linux_3_9
      if: branch = master
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.9"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge python=${PYTHONVER} coveralls coverage pandas scandir
        - pip install --pre .
      script:
        - coverage run -m unittest discover tests
      after_success:
        - coverage combine
        - coveralls
        - coverage xml
        - pip install codacy-coverage
        - python-codacy-coverage -r coverage.xml
      deploy:
        - provider: pypi
          user: pyiron
          password: ${PYPI_UPLOAD_TOKEN}
          allow_failure: true
          on:
            branch: master
        - provider: pypi
          user: pyiron
          password: ${PYPI_UPLOAD_TOKEN}
          allow_failure: true
          on:
            tags: true
