name: Pip check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.10"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment.yml
        use-mamba: true
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        pip check
